# Generated by Django 5.1.15 on 2026-10-05 18:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0004_monitor_deploy_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('website_url', models.URLField()),
                ('status_page_url', models.URLField()),
                ('feed_url', models.URLField()),
                ('adapter', models.CharField(max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('degraded', 'Degraded performance'), ('partial_outage', 'Partial outage'), ('major_outage', 'Major outage'), ('maintenance', 'Under maintenance'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('status_description', models.CharField(blank=True, max_length=200)),
                ('components', models.JSONField(blank=True, default=list)),
                ('component_count', models.PositiveIntegerField(default=0)),
                ('status_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=200)),
                ('next_poll_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['enabled', 'next_poll_at'], name='providers_p_enabled_539da2_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProviderIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=300)),
                ('impact', models.CharField(choices=[('none', 'Informational'), ('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='minor', max_length=10)),
                ('stage', models.CharField(choices=[('investigating', 'Investigating'), ('identified', 'Identified'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved')], default='investigating', max_length=16)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('updates', models.JSONField(blank=True, default=list)),
                ('affected', models.JSONField(blank=True, default=list)),
                ('first_seen_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='providers.provider')),
            ],
            options={
                'indexes': [models.Index(fields=['provider', '-started_at'], name='providers_p_provide_ae8685_idx'), models.Index(fields=['-started_at'], name='providers_p_started_7c397e_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_id'), name='one_incident_per_provider_ref')],
            },
        ),
        migrations.CreateModel(
            name='UserProviderSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_impact', models.CharField(choices=[('none', 'Any incident'), ('minor', 'Minor and above'), ('major', 'Major and above')], default='minor', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert_contacts', models.ManyToManyField(blank=True, related_name='provider_subscriptions', to='monitoring.alertcontact')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='providers.provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='providers_u_user_id_c23a58_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'provider'), name='one_subscription_per_provider')],
            },
        ),
    ]
