# Generated by Django 5.1.15 on 2026-10-05 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0003_alertcontact_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckRollupDaily',
            fields=[
                ('up', models.PositiveIntegerField(default=0)),
                ('down', models.PositiveIntegerField(default=0)),
                ('inconclusive', models.PositiveIntegerField(default=0)),
                ('down_excluded', models.PositiveIntegerField(default=0)),
                ('response_count', models.PositiveIntegerField(default=0)),
                ('response_sum_ms', models.BigIntegerField(default=0)),
                ('response_min_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('response_max_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('p50_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('p95_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('timing_count', models.PositiveIntegerField(default=0)),
                ('dns_sum_ms', models.BigIntegerField(default=0)),
                ('tcp_sum_ms', models.BigIntegerField(default=0)),
                ('tls_sum_ms', models.BigIntegerField(default=0)),
                ('ttfb_sum_ms', models.BigIntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='monitoring.monitor')),
            ],
            options={
                'indexes': [models.Index(fields=['monitor', '-day'], name='analytics_c_monitor_6f5648_idx')],
                'constraints': [models.UniqueConstraint(fields=('monitor', 'day'), name='one_daily_rollup')],
            },
        ),
        migrations.CreateModel(
            name='CheckRollupHourly',
            fields=[
                ('up', models.PositiveIntegerField(default=0)),
                ('down', models.PositiveIntegerField(default=0)),
                ('inconclusive', models.PositiveIntegerField(default=0)),
                ('down_excluded', models.PositiveIntegerField(default=0)),
                ('response_count', models.PositiveIntegerField(default=0)),
                ('response_sum_ms', models.BigIntegerField(default=0)),
                ('response_min_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('response_max_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('p50_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('p95_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('timing_count', models.PositiveIntegerField(default=0)),
                ('dns_sum_ms', models.BigIntegerField(default=0)),
                ('tcp_sum_ms', models.BigIntegerField(default=0)),
                ('tls_sum_ms', models.BigIntegerField(default=0)),
                ('ttfb_sum_ms', models.BigIntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hour', models.DateTimeField()),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='monitoring.monitor')),
            ],
            options={
                'indexes': [models.Index(fields=['monitor', '-hour'], name='analytics_c_monitor_4e0900_idx')],
                'constraints': [models.UniqueConstraint(fields=('monitor', 'hour'), name='one_hourly_rollup')],
            },
        ),
        migrations.CreateModel(
            name='FleetSummaryDaily',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('monitors', models.PositiveIntegerField(default=0)),
                ('up', models.PositiveIntegerField(default=0)),
                ('down', models.PositiveIntegerField(default=0)),
                ('inconclusive', models.PositiveIntegerField(default=0)),
                ('down_excluded', models.PositiveIntegerField(default=0)),
                ('response_count', models.PositiveIntegerField(default=0)),
                ('response_sum_ms', models.BigIntegerField(default=0)),
                ('incidents_opened', models.PositiveIntegerField(default=0)),
                ('incident_downtime_seconds', models.PositiveIntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-day'], name='analytics_f_user_id_b42e12_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'day'), name='one_fleet_summary_per_day')],
            },
        ),
    ]
