"""The deployment files (Dockerfile, entrypoint, gunicorn, the Render blueprint, the env example)
and the settings they rely on. A deploy fails in ways no other test sees: a variable the blueprint
forgot, a worker timeout shorter than the scheduler call, a container running as root. These guard
the connections between the files."""

import importlib.util
import re
from pathlib import Path

import pytest
import yaml
from django.conf import settings

ROOT = Path(__file__).resolve().parent.parent


def read(name: str) -> str:
    return (ROOT / name).read_text(encoding="utf-8")


def blueprint_vars() -> dict[str, dict]:
    service = yaml.safe_load(read("render.yaml"))["services"][0]
    return {entry["key"]: entry for entry in service["envVars"]}


def env_example_names() -> set[str]:
    names = set()
    for line in read(".env.example").splitlines():
        match = re.match(r"^#?\s*([A-Z][A-Z0-9_]+)=", line)
        if match:
            names.add(match.group(1))
    return names


# --- the blueprint ------------------------------------------------------------------------------


def test_the_blueprint_describes_one_free_docker_web_service_with_a_health_check():
    service = yaml.safe_load(read("render.yaml"))["services"][0]
    assert service["type"] == "web"
    assert service["runtime"] == "docker"
    assert service["plan"] == "free"  # the whole product is $0
    assert service["healthCheckPath"] == "/health/"


def test_the_blueprint_never_holds_a_secret_value():
    """A secret is either generated by Render or asked for (`sync: false`); a literal here would
    be committed to git."""
    secretish = re.compile(r"(SECRET|TOKEN|PASSWORD|DSN|PRIVATE_KEY|DATABASE_URL|API_KEY)")
    for key, entry in blueprint_vars().items():
        if secretish.search(key):
            assert "value" not in entry, f"{key} has a literal value in render.yaml"


def test_production_is_not_debug_and_has_a_generated_secret_key():
    env = blueprint_vars()
    assert env["DJANGO_DEBUG"]["value"] == "false"
    assert env["DJANGO_SECRET_KEY"].get("generateValue") is True
    # The website (Vercel) proxies the API, then Render's balancer: two hops, and a first-party
    # cookie. Both settings must change together, or sign-in or rate limits break.
    assert env["NUM_PROXIES"]["value"] == "2"
    assert env["AUTH_REFRESH_COOKIE_SAMESITE"]["value"] == "Lax"


def test_every_variable_in_the_blueprint_is_one_the_code_reads():
    sources = "\n".join(
        p.read_text(encoding="utf-8", errors="ignore")
        for p in list(ROOT.glob("config/*.py"))
        + list(ROOT.glob("*/*.py"))
        + list(ROOT.glob("*/management/commands/*.py"))
        + [ROOT / "gunicorn.conf.py"]
    )
    unread = [k for k in blueprint_vars() if f'"{k}"' not in sources and f"'{k}'" not in sources]
    assert unread == [], f"render.yaml sets variables nothing reads: {unread}"


def test_every_variable_the_settings_read_is_in_the_env_example_or_the_blueprint():
    """A setting you can't discover is a setting you can't configure. The few that are managed
    elsewhere are listed here on purpose."""
    managed_elsewhere = {
        "DB_NAME",
        "DB_USER",
        "DB_PASSWORD",
        "DB_HOST",
        "DB_PORT",  # local docker-compose DB
        "TEST_DATABASE",  # tests only
        "PORT",  # set by the platform
        "RENDER_GIT_COMMIT",  # set by the platform
    }
    names = set(
        re.findall(
            r'(?:environ\.get|env_bool|env_list)\(\s*"([A-Z0-9_]+)"', read("config/settings.py")
        )
    )
    known = env_example_names() | set(blueprint_vars()) | managed_elsewhere
    assert sorted(names - known) == []


def test_the_preflight_only_asks_about_variables_that_can_be_set():
    asked = set(re.findall(r'(?:get|need_https_url)\("([A-Z0-9_]+)"', read("scripts/preflight.py")))
    asked |= set(re.findall(r'env\.get\("([A-Z0-9_]+)"', read("scripts/preflight.py")))
    known = env_example_names() | set(blueprint_vars()) | {"RENDER_EXTERNAL_HOSTNAME"}
    assert asked  # the pattern above must keep matching, or this test checks nothing
    assert sorted(asked - known) == []


# --- the image ----------------------------------------------------------------------------------


def test_the_container_runs_as_an_unprivileged_user_and_migrates_before_serving():
    dockerfile = read("Dockerfile")
    assert re.search(r"^USER rootpulse$", dockerfile, re.M), "the image runs as root"
    assert "ENTRYPOINT" in dockerfile and "docker-entrypoint.sh" in dockerfile
    entrypoint = read("docker-entrypoint.sh")
    assert "manage.py migrate --noinput" in entrypoint
    assert 'exec "$@"' in entrypoint  # gunicorn must be PID 1's replacement, to get signals
    assert "set -e" in entrypoint  # a failed migration must stop the container


def test_a_build_that_cannot_collect_static_files_fails_rather_than_shipping_without_them():
    dockerfile = read("Dockerfile")
    collect = [line for line in dockerfile.splitlines() if "collectstatic" in line]
    assert collect
    assert not any("|| true" in line for line in collect)


def test_the_entrypoint_script_has_unix_line_endings_so_it_runs_in_linux():
    assert b"\r" not in (ROOT / "docker-entrypoint.sh").read_bytes()


def test_the_image_leaves_out_what_it_does_not_need():
    ignored = read(".dockerignore").split()
    for needed_out in (".env", ".git/", ".venv/", "tests/", "workers/", "db.sqlite3"):
        assert needed_out in ignored, f"{needed_out} would be copied into the image"


# --- gunicorn and the scheduler call -----------------------------------------------------------


def load_gunicorn_conf(monkeypatch, **env):
    for key, value in env.items():
        monkeypatch.setenv(key, value)
    spec = importlib.util.spec_from_file_location("gunicorn_conf", ROOT / "gunicorn.conf.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_gunicorn_listens_where_the_platform_says(monkeypatch):
    assert load_gunicorn_conf(monkeypatch, PORT="10000").bind == "0.0.0.0:10000"


def test_a_gunicorn_worker_outlives_the_whole_scheduler_call(monkeypatch):
    """The trigger runs a full pass inside one request. If gunicorn's timeout were shorter than
    that, it would kill the worker mid-pass and drop alerts."""
    conf = load_gunicorn_conf(monkeypatch)
    assert conf.timeout >= settings.TRIGGER_BUDGET_SECONDS + 30


def test_the_trigger_budget_fits_inside_the_callers_timeouts():
    workflow = read(".github/workflows/scheduler.yml")
    curl_limit = int(re.search(r"--max-time (\d+)", workflow).group(1))
    assert settings.TRIGGER_BUDGET_SECONDS < curl_limit
    # ...and the checks' own budget leaves room for dependency reads and alerts after it.
    assert settings.CHECK_PASS_BUDGET_SECONDS + settings.PROVIDER_PASS_BUDGET_SECONDS > 0
    assert settings.CHECK_PASS_BUDGET_SECONDS < settings.TRIGGER_BUDGET_SECONDS


def test_the_access_log_does_not_record_query_strings(monkeypatch):
    conf = load_gunicorn_conf(monkeypatch)
    assert "%(r)s" not in conf.access_log_format  # %(r)s is the whole request line, query and all
    assert "%(U)s" in conf.access_log_format  # the path only


# --- settings -----------------------------------------------------------------------------------


def test_static_files_are_served_by_whitenoise_right_after_the_security_middleware():
    middleware = settings.MIDDLEWARE
    assert middleware[0] == "django.middleware.security.SecurityMiddleware"
    assert middleware[1] == "whitenoise.middleware.WhiteNoiseMiddleware"
    assert settings.STORAGES["staticfiles"]["BACKEND"].startswith("whitenoise.")


def test_the_platforms_own_hostname_is_allowed_automatically():
    source = read("config/settings.py")
    assert "RENDER_EXTERNAL_HOSTNAME" in source


def test_error_tracking_never_collects_personal_data_or_request_bodies():
    source = read("config/settings.py")
    block = source[source.index("sentry_sdk.init(") :]
    assert "send_default_pii=False" in block
    assert 'max_request_body_size="never"' in block
    assert "traces_sample_rate=0" in block


def test_error_tracking_stays_off_without_a_dsn():
    assert settings.SENTRY_DSN == ""
    assert "if SENTRY_DSN and not DEBUG" in read("config/settings.py")


@pytest.mark.parametrize("value", ["", "Lax", "Strict", "None"])
def test_a_blank_cookie_setting_falls_back_to_the_default(monkeypatch, value):
    """`.env.example` ships the line commented out, but a blank `AUTH_REFRESH_COOKIE_SAMESITE=`
    must not become an empty (invalid) SameSite attribute."""
    monkeypatch.setenv("AUTH_REFRESH_COOKIE_SAMESITE", value)
    spec = importlib.util.spec_from_file_location(
        "cookie_probe_settings", ROOT / "config" / "settings.py"
    )
    module = importlib.util.module_from_spec(spec)
    monkeypatch.setenv("DJANGO_DEBUG", "true")
    spec.loader.exec_module(module)
    assert module.AUTH_REFRESH_COOKIE_SAMESITE == (value or "Strict")


@pytest.mark.parametrize("name", ["scheduler", "rollups"])
def test_the_cron_workflows_stay_quiet_until_their_secrets_exist(name):
    """A fresh clone has no secrets; the cron must not fail (and email) every few minutes. But
    a half-configured one (one secret, not both) is a mistake and must fail loudly."""
    run = read(f".github/workflows/{name}.yml")
    skip = run.index("are not set; skipping")
    assert "exit 0" in run[skip : skip + 100]
    assert '[ -z "${API_URL:-}" ] && [ -z "${SCHEDULER_SHARED_SECRET:-}" ]' in run
    assert "must both be set" in run


def test_the_blueprint_does_not_use_an_smtp_port_render_blocks_on_the_free_tier():
    port = int(blueprint_vars()["EMAIL_PORT"]["value"])
    assert port not in {25, 465, 587}, "Render's free tier blocks outbound SMTP on this port"
