# Generated by Django 5.1.15 on 2026-10-05 20:02

import django.db.models.deletion
import statuspages.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0003_incident_deploy_incident_root_cause_and_more'),
        ('monitoring', '0004_monitor_deploy_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('password_hash', models.CharField(blank=True, max_length=256)),
                ('is_public', models.BooleanField(default=False)),
                ('branding', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_pages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StatusPageAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('incident', 'Incident'), ('maintenance', 'Maintenance')], max_length=16)),
                ('impact', models.CharField(choices=[('none', 'Informational'), ('minor', 'Minor'), ('major', 'Major')], default='none', max_length=8)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(blank=True, max_length=2000)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='statuspages.statuspage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusPageComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=80)),
                ('group', models.CharField(blank=True, max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_page_components', to='monitoring.monitor')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='statuspages.statuspage')),
            ],
            options={
                'ordering': ['order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='StatusPageSubscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirm_token', models.CharField(blank=True, default=statuspages.models.new_token, max_length=64)),
                ('confirmations_sent', models.PositiveSmallIntegerField(default=0)),
                ('last_confirmation_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribe_token', models.CharField(default=statuspages.models.new_token, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='statuspages.statuspage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusPageEmail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('confirm', 'Confirm subscription'), ('incident_opened', 'Component down'), ('incident_resolved', 'Component recovered'), ('announcement', 'Announcement posted'), ('announcement_resolved', 'Announcement resolved')], max_length=24)),
                ('dedupe_key', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='statuspages.statuspageannouncement')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='incidents.incident')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='statuspages.statuspagesubscriber')),
            ],
        ),
        migrations.AddIndex(
            model_name='statuspage',
            index=models.Index(fields=['user'], name='statuspages_user_id_04baff_idx'),
        ),
        migrations.AddIndex(
            model_name='statuspageannouncement',
            index=models.Index(fields=['page', '-created_at'], name='statuspages_page_id_17363a_idx'),
        ),
        migrations.AddConstraint(
            model_name='statuspagecomponent',
            constraint=models.UniqueConstraint(fields=('page', 'monitor'), name='one_component_per_monitor'),
        ),
        migrations.AddIndex(
            model_name='statuspagesubscriber',
            index=models.Index(fields=['confirm_token'], name='statuspages_confirm_229fe1_idx'),
        ),
        migrations.AddConstraint(
            model_name='statuspagesubscriber',
            constraint=models.UniqueConstraint(fields=('page', 'email'), name='one_subscription_per_email'),
        ),
        migrations.AddIndex(
            model_name='statuspageemail',
            index=models.Index(fields=['status', 'next_attempt_at'], name='statuspages_status_581905_idx'),
        ),
        migrations.AddConstraint(
            model_name='statuspageemail',
            constraint=models.UniqueConstraint(fields=('subscriber', 'dedupe_key'), name='one_email_per_subscriber_and_event'),
        ),
        migrations.AddConstraint(
            model_name='statuspageemail',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('next_attempt_at__isnull', False), ('status', 'pending')), models.Q(('status', 'pending'), _negated=True), _connector='OR'), name='pending_status_emails_have_a_due_time'),
        ),
    ]
