"""Deploys: "something shipped", so an incident that follows can say so.

A `DeploySource` is one connection (a GitHub repo's webhook, a Vercel project, a Render
service, or a CI step calling our generic endpoint). It has its own URL and signing secret, which
is also how an incoming request is attributed to a user. Each successful deploy it reports
becomes a `Deploy`.
"""

from __future__ import annotations

import secrets
import uuid

from django.conf import settings
from django.db import models
from django.db.models import Q


def new_token() -> str:
    return secrets.token_urlsafe(16)


class DeploySource(models.Model):
    class Type(models.TextChoices):
        GITHUB = "github", "GitHub"
        VERCEL = "vercel", "Vercel"
        RENDER = "render", "Render"
        GENERIC = "generic", "Generic / CI"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="deploy_sources"
    )
    name = models.CharField(max_length=120)
    type = models.CharField(max_length=16, choices=Type.choices)
    # The secret path segment of this source's webhook URL. It says whose deploy this is; the
    # signature (below) says the request is genuine.
    token = models.CharField(max_length=32, unique=True, default=new_token)
    # The key requests are signed with. Generated by us for GitHub and generic sources (shown
    # once); for Vercel and Render it is the signing secret the provider issued.
    secret = models.CharField(max_length=255)
    # Only count deploys to this environment ("production"). Blank = all.
    environment_filter = models.CharField(max_length=60, blank=True)
    enabled = models.BooleanField(default=True)
    last_received_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        indexes = [models.Index(fields=["user", "created_at"])]

    def __str__(self) -> str:
        return f"{self.name} ({self.type})"


class Deploy(models.Model):
    """One successful deploy, as reported by a source."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="deploys"
    )
    # SET_NULL: deleting a source keeps the history of what it reported.
    source = models.ForeignKey(
        DeploySource, null=True, on_delete=models.SET_NULL, related_name="deploys"
    )
    source_type = models.CharField(max_length=16)
    source_name = models.CharField(max_length=120)
    # Makes ingestion idempotent: a provider's retry or replay of the same deploy is a no-op.
    external_id = models.CharField(max_length=128)
    service_name = models.CharField(max_length=150)
    # Everything this deploy answers to, lower-cased: the service name, plus e.g. a repo's full
    # "owner/name". A monitor's `deploy_service` has to equal one of these.
    names = models.JSONField(default=list)
    environment = models.CharField(max_length=60, blank=True)
    version = models.CharField(max_length=80, blank=True)
    url = models.CharField(max_length=500, blank=True)
    occurred_at = models.DateTimeField()
    received_at = models.DateTimeField(auto_now_add=True)
    # What the provider sent, trimmed (see deploys.services.MAX_RAW_BYTES).
    raw_payload = models.JSONField(default=dict, blank=True)

    class Meta:
        indexes = [models.Index(fields=["user", "-occurred_at"])]
        constraints = [
            models.UniqueConstraint(
                fields=["source", "external_id"],
                condition=Q(source__isnull=False),
                name="one_deploy_per_source_ref",
            )
        ]

    def __str__(self) -> str:
        return f"{self.service_name} {self.version or self.external_id}"
