# Generated by Django 5.1.15 on 2026-10-03 22:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auditlog_nullable_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('purpose', models.CharField(choices=[('signup', 'Sign up'), ('login', 'Log in')], max_length=8)),
                ('link_hash', models.CharField(max_length=64, unique=True)),
                ('code_hash', models.CharField(max_length=64)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email', '-created_at'], name='accounts_em_email_aa383b_idx')],
            },
        ),
    ]
