# Generated by Django 5.1.15 on 2026-10-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailchallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
