# Generated by Django 5.1.15 on 2026-10-05 17:11

import deploys.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploySource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('github', 'GitHub'), ('vercel', 'Vercel'), ('render', 'Render'), ('generic', 'Generic / CI')], max_length=16)),
                ('token', models.CharField(default=deploys.models.new_token, max_length=32, unique=True)),
                ('secret', models.CharField(max_length=255)),
                ('environment_filter', models.CharField(blank=True, max_length=60)),
                ('enabled', models.BooleanField(default=True)),
                ('last_received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deploy_sources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deploy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(max_length=16)),
                ('source_name', models.CharField(max_length=120)),
                ('external_id', models.CharField(max_length=128)),
                ('service_name', models.CharField(max_length=150)),
                ('names', models.JSONField(default=list)),
                ('environment', models.CharField(blank=True, max_length=60)),
                ('version', models.CharField(blank=True, max_length=80)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('occurred_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deploys', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deploys', to='deploys.deploysource')),
            ],
        ),
        migrations.AddIndex(
            model_name='deploysource',
            index=models.Index(fields=['user', 'created_at'], name='deploys_dep_user_id_a4aa36_idx'),
        ),
        migrations.AddIndex(
            model_name='deploy',
            index=models.Index(fields=['user', '-occurred_at'], name='deploys_dep_user_id_33abf4_idx'),
        ),
        migrations.AddConstraint(
            model_name='deploy',
            constraint=models.UniqueConstraint(condition=models.Q(('source__isnull', False)), fields=('source', 'external_id'), name='one_deploy_per_source_ref'),
        ),
    ]
