# Generated by Django 5.1.15 on 2026-10-04 12:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('webhook', 'Webhook'), ('telegram', 'Telegram'), ('discord', 'Discord'), ('slack', 'Slack'), ('push', 'Web push')], max_length=16)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('delay_seconds', models.PositiveIntegerField(default=0)),
                ('repeat_interval_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('http', 'HTTP(S)'), ('keyword', 'Keyword'), ('ping', 'Ping'), ('port', 'Port'), ('ssl', 'SSL certificate'), ('domain', 'Domain expiration'), ('cron', 'Heartbeat'), ('dns', 'DNS')], max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('target', models.CharField(blank=True, max_length=2048)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('interval_seconds', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('up', 'Up'), ('down', 'Down'), ('paused', 'Paused')], default='pending', max_length=16)),
                ('next_check_at', models.DateTimeField(blank=True, null=True)),
                ('last_check_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('recurrence_rule', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_windows', to=settings.AUTH_USER_MODEL)),
                ('monitors', models.ManyToManyField(blank=True, related_name='maintenance_windows', to='monitoring.monitor')),
            ],
        ),
        migrations.CreateModel(
            name='MonitorAlertContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.alertcontact')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.monitor')),
            ],
        ),
        migrations.AddField(
            model_name='monitor',
            name='alert_contacts',
            field=models.ManyToManyField(blank=True, related_name='monitors', through='monitoring.MonitorAlertContact', to='monitoring.alertcontact'),
        ),
        migrations.AddIndex(
            model_name='alertcontact',
            index=models.Index(fields=['user'], name='monitoring__user_id_8d2448_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancewindow',
            index=models.Index(fields=['starts_at', 'ends_at'], name='monitoring__starts__4fb1af_idx'),
        ),
        migrations.AddConstraint(
            model_name='maintenancewindow',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='maintenance_ends_after_start'),
        ),
        migrations.AddConstraint(
            model_name='monitoralertcontact',
            constraint=models.UniqueConstraint(fields=('monitor', 'alert_contact'), name='unique_monitor_alert_contact'),
        ),
        migrations.AddIndex(
            model_name='monitor',
            index=models.Index(fields=['next_check_at'], name='monitoring__next_ch_735cb6_idx'),
        ),
        migrations.AddIndex(
            model_name='monitor',
            index=models.Index(fields=['user', '-created_at'], name='monitoring__user_id_1376e1_idx'),
        ),
        migrations.AddIndex(
            model_name='monitor',
            index=models.Index(fields=['user', 'status'], name='monitoring__user_id_ea76ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='monitor',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('heartbeat_token__isnull', False), ('type', 'cron')), models.Q(models.Q(('type', 'cron'), _negated=True), ('heartbeat_token__isnull', True)), _connector='OR'), name='heartbeat_token_only_on_cron'),
        ),
        migrations.AddConstraint(
            model_name='monitor',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'paused'), _negated=True), ('next_check_at__isnull', True), _connector='OR'), name='paused_monitors_are_never_due'),
        ),
    ]
