# Generated by Django 5.1.15 on 2026-10-04 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='last_response_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='last_status_detail',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='monitor',
            name='state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=32)),
                ('confirmation', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField()),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(null=True)),
                ('status_detail', models.CharField(blank=True, max_length=64)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dns_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('tcp_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('tls_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('ttfb_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='monitoring.monitor')),
            ],
            options={
                'indexes': [models.Index(fields=['monitor', '-started_at'], name='monitoring__monitor_eb47cf_idx'), models.Index(fields=['started_at'], name='monitoring__started_0368ed_idx')],
            },
        ),
    ]
