# Generated by Django 5.1.15 on 2026-10-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_checks_and_engine_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertcontact',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alertcontact',
            name='verification_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alertcontact',
            name='verification_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertcontact',
            name='verification_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='alertcontact',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
