# Generated by Django 5.1.15 on 2026-10-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alertcontact_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='deploy_service',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
