# Generated by Django 5.1.15 on 2026-10-04 14:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0002_checks_and_engine_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(max_length=64)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=16)),
                ('excluded_from_reports', models.BooleanField(default=False)),
                ('root_cause_stage', models.CharField(blank=True, max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='monitoring.monitor')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='monitoring.check')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='monitoring.check')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(max_length=5000)),
                ('visible_on_status_page', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='incidents.incident')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('opened', 'Opened'), ('recheck_confirmed', 'Confirmed by re-check'), ('resolved', 'Resolved'), ('closed_paused', 'Closed: monitor paused'), ('closed_edited', 'Closed: monitor changed'), ('excluded', 'Excluded from reports'), ('included', 'Included in reports')], max_length=24)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField()),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='incidents.incident')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['monitor', '-started_at'], name='incidents_i_monitor_fe1924_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['-started_at'], name='incidents_i_started_926e09_idx'),
        ),
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('monitor',), name='one_open_incident_per_monitor'),
        ),
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='incident_ends_after_it_starts'),
        ),
        migrations.AddIndex(
            model_name='incidentcomment',
            index=models.Index(fields=['incident', 'created_at'], name='incidents_i_inciden_31683d_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentevent',
            index=models.Index(fields=['incident', 'created_at'], name='incidents_i_inciden_a6ec40_idx'),
        ),
    ]
