# Generated by Django 5.1.15 on 2026-10-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentevent',
            name='kind',
            field=models.CharField(choices=[('opened', 'Opened'), ('recheck_confirmed', 'Confirmed by re-check'), ('resolved', 'Resolved'), ('closed_paused', 'Closed: monitor paused'), ('closed_edited', 'Closed: monitor changed'), ('excluded', 'Excluded from reports'), ('included', 'Included in reports'), ('notification_sent', 'Alert sent'), ('notification_failed', 'Alert failed')], max_length=24),
        ),
    ]
