# Generated by Django 5.1.15 on 2026-10-05 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploys', '0001_initial'),
        ('incidents', '0002_alter_incidentevent_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='deploy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='deploys.deploy'),
        ),
        migrations.AddField(
            model_name='incident',
            name='root_cause',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='incidentevent',
            name='kind',
            field=models.CharField(choices=[('opened', 'Opened'), ('recheck_confirmed', 'Confirmed by re-check'), ('resolved', 'Resolved'), ('closed_paused', 'Closed: monitor paused'), ('closed_edited', 'Closed: monitor changed'), ('excluded', 'Excluded from reports'), ('included', 'Included in reports'), ('notification_sent', 'Alert sent'), ('notification_failed', 'Alert failed'), ('deploy_linked', 'Linked to a deploy')], max_length=24),
        ),
    ]
