# Generated by Django 5.1.15 on 2026-10-04 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0002_alter_incidentevent_kind'),
        ('monitoring', '0003_alertcontact_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=120)),
                ('channel', models.CharField(max_length=16)),
                ('event', models.CharField(choices=[('opened', 'Incident opened'), ('reminder', 'Still down'), ('resolved', 'Recovered'), ('test', 'Test')], max_length=16)),
                ('dedupe_key', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='monitoring.alertcontact')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='incidents.incident')),
                ('monitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='monitoring.monitor')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='notificatio_status_e1aed1_idx'), models.Index(fields=['incident', '-created_at'], name='notificatio_inciden_ed0ee8_idx'), models.Index(fields=['monitor', '-created_at'], name='notificatio_monitor_e2d317_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('contact__isnull', False), ('incident__isnull', False)), fields=('incident', 'contact', 'dedupe_key'), name='one_delivery_per_incident_contact_event'), models.CheckConstraint(condition=models.Q(models.Q(('next_attempt_at__isnull', False), ('status', 'pending')), models.Q(('status', 'pending'), _negated=True), _connector='OR'), name='pending_deliveries_have_a_due_time')],
            },
        ),
    ]
