# Generated by Django 5.1.15 on 2026-10-05 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_incident_deploy_incident_root_cause_and_more'),
        ('monitoring', '0004_monitor_deploy_service'),
        ('notifications', '0002_integration_links'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdelivery',
            name='provider_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='providers.providerincident'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(condition=models.Q(('contact__isnull', False), ('provider_incident__isnull', False)), fields=('provider_incident', 'contact', 'dedupe_key'), name='one_delivery_per_provider_incident_contact_event'),
        ),
    ]
